name: gg_store_cashier
description: "GG Store Cashier - Point of Sale Flutter Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  dotted_border: ^2.1.0

  # Image
  image_picker: ^1.0.7
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  socket_io_client: ^2.0.3+1
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  # Animations
  animations: ^2.0.11
  lottie: ^3.1.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  
  # Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    # - assets/icons/
    - assets/products/
